version: '3.8'

services:
  redis:
    image: redis:7
    container_name: gateway-redis
    ports:
      - "6379:6379"
    restart: always

  user-db:
    image: postgres:15
    container_name: user-postgres
    ports:
      - "5432:5432" 
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: userservice
    volumes:
      - user-db-data:/var/lib/postgresql/data
    restart: always

volumes:
  user-db-data: