server:
  port: 8081
spring:
  threads:
    virtual:
      enabled: true
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
