server:
  port:
    8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/userservice
    username: postgres
    password: naman@456

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true