server:
  port: 8082

spring:
  application:
    name: analytics-service
  datasource:
    url: jdbc:postgresql://localhost:5433/analytics_db
    username: postgres
    password: your_password
    jpa:
      hibernate:
        ddl-auto: update
  kafka:
    listener:
      type: batch
    bootstrap-servers: localhost:9092
    consumer:
      max-poll-records: 500
      group-id: analytics-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.use.type.headers: false
        spring.json.trusted.packages: "*"
        spring.json.value.default.type: com.major.analytics_service.dto.AnalyticsEvent